First we started by reading the csv file 'captions.txt' and then displaying the first five rows

In [2]:

from os import truncate

import pandas as pd

captions_path = "../data/captions/captions.txt"

df = pd.read_csv(captions_path)
print(df.head())


                       image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  
0  A child in a pink dress is climbing up a set o...  
1              A girl going into a wooden building .  
2   A little girl climbing into a wooden playhouse .  
3  A little girl climbing the stairs to her playh...  
4  A little girl in a pink dress going into a woo...  


Now we want group all rows that have the same image filename together, keeping only the caption column, then for each group we convert all captions into a python list, and finally convert the pandas object into a dictionary

In [3]:
image_to_captions = (
    df.groupby('image')['caption'].apply(list).to_dict()
)

print("Number of images: ", len(image_to_captions))

Number of images:  8091


Creating a new column for captions in lower case and without punctuation

In [4]:

import string

#Removing the upper cases
df['lower_caption'] = df['caption'].str.lower()

#Function to remove the punctuation
def remove_punctuation(lower_caption):
    for char in string.punctuation:
        lower_caption = lower_caption.replace(char, '')
    return lower_caption

df['lower_caption'] = df['lower_caption'].apply(remove_punctuation)

#Comparing the new column with the old column
df.sample(10)



image  \
2628   1474474514_b3eb492722.jpg   
9546   2445654384_4ee3e486e1.jpg   
9381   2432709509_2a4d0c833f.jpg   
1016   1245022983_fb329886dd.jpg   
22682  3215117062_6e07a86352.jpg   
6638   2252299132_14ca6e584b.jpg   
32766  3618504267_d7eaa495d0.jpg   
37917   514073775_56796be990.jpg   
86     1022454428_b6b660a67b.jpg   
11159  2548777800_d7b9cf1c2b.jpg   

                                                 caption  \
2628   A young boy wearing Mickey Mouse clothes in a ...   
9546   A man in a black shirt is holding a child wear...   
9381   A child is sitting on the grass by a concrete ...   
1016   A little girl in pink dances with her hands on...   
22682  The people are standing around at the auto show .   
6638   a young boy running a race on a track with a p...   
32766  A man and a woman walk their small dogs at an ...   
37917  group of kids outside a building reaching for ...   
86     A couple sit on the grass with a baby and stro...   
11159  The boy wearing orange face paint is carrying ...   

                                           lower_caption  
2628   a young boy wearing mickey mouse clothes in a ...  
9546   a man in a black shirt is holding a child wear...  
9381   a child is sitting on the grass by a concrete ...  
1016   a little girl in pink dances with her hands on...  
22682   the people are standing around at the auto show   
6638   a young boy running a race on a track with a p...  
32766  a man and a woman walk their small dogs at an ...  
37917  group of kids outside a building reaching for ...  
86     a couple sit on the grass with a baby and stro...  
11159  the boy wearing orange face paint is carrying ...

Tokenization for each caption

In [5]:

import nltk
from nltk.tokenize import word_tokenize
#Was having trouble with the import word_tokenize so had to add the line below
#nltk.download('punkt_tab')

#Creating a new column for tokens for each caption
df['tokens'] = df['lower_caption'].apply(lambda x: word_tokenize(x))
df.head()






image  \
0  1000268201_693b08cb0e.jpg   
1  1000268201_693b08cb0e.jpg   
2  1000268201_693b08cb0e.jpg   
3  1000268201_693b08cb0e.jpg   
4  1000268201_693b08cb0e.jpg   

                                             caption  \
0  A child in a pink dress is climbing up a set o...   
1              A girl going into a wooden building .   
2   A little girl climbing into a wooden playhouse .   
3  A little girl climbing the stairs to her playh...   
4  A little girl in a pink dress going into a woo...   

                                       lower_caption  \
0  a child in a pink dress is climbing up a set o...   
1               a girl going into a wooden building    
2    a little girl climbing into a wooden playhouse    
3  a little girl climbing the stairs to her playh...   
4  a little girl in a pink dress going into a woo...   

                                              tokens  
0  [a, child, in, a, pink, dress, is, climbing, u...  
1        [a, girl, going, into, a, wooden, building]  
2  [a, little, girl, climbing, into, a, wooden, p...  
3  [a, little, girl, climbing, the, stairs, to, h...  
4  [a, little, girl, in, a, pink, dress, going, i...

Building the vocabulary

In [6]:
from collections import Counter

#Couting all the words
word_counter = Counter()

for i in df['tokens']:
    word_counter.update(i)

#Defining special tokens
#To fill empty positions
PAD_TOKEN = "<PAD>"
#When a word is not in the vocabulary
UNK_TOKEN = "<UNK>"

#Creating a vocabulary
word_to_idx = {
    PAD_TOKEN: 0,
    UNK_TOKEN: 1
}

for word in word_counter:
    #Auto increments the ID generator
    word_to_idx[word] = len(word_to_idx)


print("Vocabulary size:", len(word_to_idx))
print("Sample entries:", list(word_to_idx.items())[:10])


Vocabulary size: 8829
Sample entries: [('<PAD>', 0), ('<UNK>', 1), ('a', 2), ('child', 3), ('in', 4), ('pink', 5), ('dress', 6), ('is', 7), ('climbing', 8), ('up', 9)]


Convert the tokens to integers


In [7]:

#Creating a variable for unk token index
UNK_IDX = word_to_idx[UNK_TOKEN]

sequence = []

#For loop to check if the word is in the tokens dataframe; if it is just adds the index; if it's not it will add the unk index
for tokens in df['tokens']:
    seq = []
    for word in tokens:
        if word in word_to_idx:
            seq.append(word_to_idx[word])
        else:
            seq.append(UNK_IDX)
    #Appending to the empty sequence list
    sequence.append(seq)

print("Original: ", df['tokens'][1])
print("Sequence: ", sequence[1])



Original:  ['a', 'girl', 'going', 'into', 'a', 'wooden', 'building']
Sequence:  [2, 16, 17, 18, 2, 19, 20]


Organizing

In [8]:

#Dropping caption, and lower_caption columns to organize the dataframe since they aren't useful anymore
#Inplace = True to change the original and don't give us just a copy
df.drop(['caption', 'lower_caption'], axis= 'columns', inplace= True)


Sequence padding and truncating


In [33]:

#Checking the biggest sequence and the 95%
import numpy as np
lengths = [len(i) for i in sequence]
print(f"Max: {max(lengths)}, 95th percentile: {np.percentile(lengths, 95)}")

#Truncating sequences > 20
#Padding sequences < 20
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 20

padded_sequences = pad_sequences(
    sequence,
    maxlen = max_length,
    #Padding at the end
    padding = 'post',
    #Truncating at the end
    truncating = 'post'
)

#Printing the first 20 sequences as numpy arrays
print(padded_sequences[:20])





Max: 36, 95th percentile: 18.0
[[ 2  3  4  2  5  6  7  8  9  2 10 11 12  4 13 14 15  0  0  0]
 [ 2 16 17 18  2 19 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 21 16  8 18  2 19 22  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 21 16  8 23 12 24 25 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 21 16  4  2  5  6 17 18  2 19 26  0  0  0  0  0  0  0  0]
 [ 2 27 28 29  2 30 28 31 32  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 27 28 29  2 33 28 34 35 36 37 38 23 39  0  0  0  0  0  0]
 [ 2 27 28 29  2 40 28 35 41 42 31 43 44 36 37  4 23 45  0  0]
 [46 47 11 48 49 50 44 36 37 38 23 39  0  0  0  0  0  0  0  0]
 [46 47 38 51 52 53 36 37  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 21 16 54  4 55 56  4 57 11  2 58 59 35 25 60  4  2 61  0]
 [ 2 21 16  7 62  4 57 11  2 63 58 59  0  0  0  0  0  0  0  0]
 [ 2 64 16  4 23 65 66 35 67  4 57 11  2 40 68 35  2 59 38 69]
 [70  7  2 16 35 71 62  4 57 11  2 59 72  0  0  0  0  0  0  0]
 [73 16 35 71 72 74  4 23 65  0  0  0  0  0  0  0  0  0  0  0]
 [ 2 75 76 38  2 77 78 7